Feature/syal-180
AVISPL/dal-codecs-singlecodecs-cisco pull request #1
Opened 2021-03-17 16:50 UTC by MaksimR-AVISPL

2021-04-19 21:17 UTC, ShervinM-AVISPL requested changes

2021-04-26 13:38 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +        setTrustAllCertificates(true);
Yeah, for most of them. Pretty sure it's not the case for XiO or other communicators that depend on a remote cloud api, but for all the devices with http/https protocols - yes :)

2021-04-26 16:49 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +            ValueSpaceRefHolder peoplePresenceDetectorState = configuration.getRoomAnalytics().getPeoplePresenceDetector();
well, basically it is expected that it's there if it's present in status, but just to be on the safe side - yes, it's better to have the check

2021-04-27 16:56 UTC, ShervinM-AVISPL requested changes

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +        if(isNumeric(value)) {
Missing '!'

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +                    && (value.getType().equals(ValueSpaceRefHolderType.INT) || value.getType().equals(ValueSpaceRefHolderType.VS_INT))) {
value.getType() is being extracted multiple times.

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/AudioConfigurationCommandType.java
> +public enum AudioConfigurationCommandType {
Enum members need brief javadoc, or there will be warnings. For example, MicrophoneMode could have simple java doc that looks like /** Represents the mode of microphone */

Here's an example of an enum that does not show any warnings:
 ```suggestion
public enum SimulationMode {
		/** few devices in a call, few devices violating thresholds. here 10% of devices should be in a call and another 10% violating thresholds */
		regular,
		/** few devices in a call, large number of devices violating thresholds. here 10% of devices should be in a call and another 60% violating thresholds */
		high_threshold_violation,
		/**
		 * few devices in a call, few devices violating thresholds, connection to cloud is simulated as down. here 10% of devices should be in a call and
		 * another 10% violating thresholds
		 */
		cloud_down
	}

```

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/AudioControlCommandType.java
> +    Volume
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/CameraConfigurationCommandType.java
> +    CameraFocusMode, CameraBrightnessDefaultLevel, CameraBrightnessMode, CameraBacklightDefaultMode, TriggerAutofocusPreset
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/CameraControlCommandType.java
> +    CameraPan, CameraTilt, CameraZoom, CameraFocus
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/ConferenceConfigurationCommandType.java
> +    DefaultCallRate, DoNotDisturbTimeout, EncryptionMode, FarEndControl}
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/NetworkServicesConfigurationCommandType.java
> +    H323Mode, SIPMode, TelnetMode, SSHMode, CDPMode, UPnPMode, NTPMode, WelcomeText
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/ProximityConfigurationCommandType.java
> +    ProximityMode, CallControl, ContentShareToClients, ContentShareFromClients
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/RoomAnalyticsConfigurationCommandType.java
> +    PeoplePresenseMode
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/StandbyConfigurationCommandType.java
> +    BootAction, Control, Delay, StandbyAction, WakeupAction
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/UserInterfaceConfigurationCommandType.java
> +    WhiteboardStart, HideAllFeatures, AwakeBrandingColors, IncomingCallNotification, OSDOutput
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/VideoConfigurationCommandType.java
> +    OverscanLevel, Resolution
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/controller/type/VideoSelfViewConfigurationCommandType.java
> +    DefaultFullscreenMode, DefaultMode, DefaultOnMonitorRole, DefaultPIPPosition, OnCallDuration, OnCallMode
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/ValueSpaceRefHolderType.java
> +    VS_INT, INT, STR, TTPAR, DEFAULT
Enum members javadoc missing

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/ValueSpaceRefHolder.java
> + */
special characters such as '<' will result in Symphony's javadoc generator to fail. You should use '&lt;'.
Or, you can just wrap any special characters in {@code ..... }, for example:
{@code <DviType valueSpaceRef="/Valuespace/TTPAR_DviType">AutoDetect</DviType>}

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/control/commands/call/CallDisconnectCommand.java
> +    public CallDisconnectCommand() {
public method missing javadoc

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/control/commands/call/response/CallDisconnectResult.java
> +        this.status = status;
public methods missing javadocs

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/control/commands/standby/StandbyCommand.java
> +    }
public constructors missing javadocs

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/control/commands/systemunit/SystemUnitCommand.java
> +        }
public constructors missing javadocs

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/control/commands/userinterface/UserInterfaceCommand.java
> +                }
public constructors missing javadocs

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/control/commands/userinterface/UserInterfaceCommand.java
> +        }
public constructors missing javadocs.
Please check all constructors have javadocs (sorry for such tedious tasks, but if we don't do it, we'll have too many warnings)

2021-04-27 16:56 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/valuespace/ValueSpace.java
> + *      <Protocol valueSpaceRef="/Valuespace/TTPAR_CallProtocol">Auto</Protocol>
special characters will fail on javadoc generation. Wrap then in {@code ..... }

2021-04-27 18:20 UTC, ShervinM-AVISPL approved these changes
Looks good @MaksimR-AVISPL. Please don't forget to format CiscoCommunicator class before you merge, I saw a lot of little formatting issues.

2021-04-27 19:22 UTC, merged