Feature/syal 640
AVISPL/dal-codecs-singlecodecs-cisco pull request #11
Opened 2021-12-24 12:41 UTC by MaksimR-AVISPL

2022-01-19 21:37 UTC, ShervinM-AVISPL requested changes

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +     * devices data, but in oder to retrieve registered devices also - command action is needed.
`order` is spelled wrong

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +            if (peripheralsListResult != null && "OK".equals(peripheralsListResult.getStatus())) {
is it guaranteed that keyword "OK" is always returned in upper-case format? why not `equalsIgnoreCase`

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +                    String connectedKey = String.format(PERIPHERALS_CONNECTED_TEMPLATE, connectedDevice.getType());
`connectedDevice.getType()` can be extracted and reused

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +                    String type = connectedDevice.getType();
this line should be moved up to line 1626

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +                    addStatisticsParameter(typedStats, typeKey, mergeAndNormalizeStrings(typedStats.get(typeKey), connectedDevice.getType(), "; "));
`type` can be used here too

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +     * @param valuespace             device valuespace data fetched from {@link #valuespacePath}
Since there is a javadoc for this method, and the method is new in 1.1, you can add `@since 1.1`

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +     * @return {@link String} merge result with separator
Since there is a javadoc for this method, and the method is new in 1.1, you can add `@since 1.1`

2022-01-19 21:37 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +            // TODO double check since it's jackson now
was this double-checked?

2022-01-20 13:23 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +            // TODO: double check, since it's jackson now
yes, removing the exception handling logic

2022-01-20 13:23 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/CiscoCommunicator.java
> +            // TODO double check since it's jackson now
yes, removing exception handling logic

2022-01-20 14:45 UTC, ShervinM-AVISPL approved these changes

2022-01-20 14:45 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/cisco/dto/configuration/peripherals/CiscoTouchPanels.java
> +    public CiscoTouchPanels() {
Fyi, all public methods should have javadocs, thanks for adding!

2022-01-20 14:52 UTC, merged